# Site settings
title: James Gregory
email: james@jagregory.com
description: >
  Code monkey. ThoughtWorks. Chief Agitator.
baseurl: /
url: "http://www.jagregory.com"
twitter_username: jagregory
github_username:  jagregory
excerpt_separator: '<!-- more -->'
permalink: /writings/:title

logo: false
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

plugins:
  - jekyll-feed
  - jekyll-paginate
