# Site settings
title: James Gregory
email: james@jagregory.com
description: >
  Jack of all trades, master of none. Principal Consultant at [Thoughtworks](https://www.thoughtworks.com/). Pronouns: he/him
baseurl: /
url: "https://www.jagregory.com"
twitter_username: jagregory
github_username:  jagregory
excerpt_separator: '<!-- more -->'
permalink: /writings/:title

logo: false
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

plugins:
  - jekyll-feed
  - jekyll-paginate
